// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    BacktestingLog: typeof import('./src/components/backtesting/BacktestingLog.vue')['default']
    ElAutocomplete: typeof import('element-plus/es')['ElAutocomplete']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    GridFooter: typeof import('./src/components/footer/GridFooter.vue')['default']
    GridFundsCalc: typeof import('./src/components/grid/GridFundsCalc.vue')['default']
    GridHeader: typeof import('./src/components/header/GridHeader.vue')['default']
    MiniNextPriceCard: typeof import('./src/components/predict/MiniNextPriceCard.vue')['default']
    NextPriceCard: typeof import('./src/components/predict/NextPriceCard.vue')['default']
    NextPriceTable: typeof import('./src/components/predict/NextPriceTable.vue')['default']
    StockKLine: typeof import('./src/components/kline/StockKLine.vue')['default']
    StockSearch: typeof import('./src/components/search/StockSearch.vue')['default']
    SvgIcon: typeof import('./src/components/icons/SvgIcon.vue')['default']
  }
}

export { }
